version: '3.4'
services:
  ingest:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    ports:
      - "9202:9202"
      - "9302:9302"
    configs:
      - source: elastic_ingest_conf
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx1512m -Xms1512m"
    extra_hosts:
      - "elk-nodo01:192.168.22.17"
      - "elk-nodo02:192.168.22.18"
      - "elk-nodo03:192.168.22.19"
      - "elk-coord01:192.168.22.23"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  coord:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    ports:
      - "9201:9201"
      - "9301:9301"
    configs:
      - source: elastic_coord_conf
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    extra_hosts:
      - "elk-nodo01:192.168.22.17"
      - "elk-nodo02:192.168.22.18"
      - "elk-nodo03:192.168.22.19"
      - "elk-coord01:192.168.22.23"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    ports:
      - "5601:5601"
    configs:
      - source: kibana_conf
        target: /usr/share/kibana/config/kibana.yml
    extra_hosts:
      - "elk-nodo01:192.168.22.17"
      - "elk-nodo02:192.168.22.18"
      - "elk-nodo03:192.168.22.19"
      - "elk-coord01:192.168.22.23"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
configs:
  kibana_conf:
    file: ./kibana/config/kibana.yml
  elastic_coord_conf:
    file: ./elastic_coord/config/elasticsearch.yml
  elastic_ingest_conf:
    file: ./elastic_ingest/config/elasticsearch.yml
networks:
  elk:
    driver: overlay
    attachable: true
